SimpleInvoice/SimpleInvoice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("invoice.urls")),
    path("accounts/", include("accounts.urls")), 
    path("admin/", admin.site.urls),
]
 

SimpleInvoice/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout"),
    path("signup/", views.signup_user, name="signup"),
]

SimpleInvoice/invoice/urls.py
from django.urls import path
from . import views

app_name = "invoice"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("create/", views.create_invoice, name="create"),
    path(
        "create-similar/<uuid:invoice_id>/",
        views.create_similar_invoice,
        name="create-similar",
    ),
    path("delete/<uuid:invoice_id>/", views.delete_invoice, name="delete"),
    path("detail/<uuid:invoice_id>/", views.detail_invoice, name="detail"),
    path("download/<uuid:invoice_id>/", views.download_invoice, name="download"),
    path("update/<uuid:invoice_id>/", views.update_invoice, name="update"),
]

SimpleInvoice/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import uuid


class CustomUser(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.email

SimpleInvoice/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import CustomUser


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ["email", "password"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Email address"
        self.fields["username"].widget.attrs.update({"class": "form-class"})
        self.fields["password"].label = "Password"
        self.fields["password"].widget.attrs.update({"class": "form-class"})


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ["email", "username", "password1", "password2"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Username"
        self.fields["username"].widget.attrs.update({"class": "form-class"})
        self.fields["email"].label = "Email address"
        self.fields["email"].widget.attrs.update({"class": "form-class"})
        self.fields["password1"].label = "Password"
        self.fields["password1"].widget.attrs.update({"class": "form-class"})
        self.fields["password2"].label = "Confirm password"
        self.fields["password2"].widget.attrs.update({"class": "form-class"})

SimpleInvoice/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.shortcuts import redirect, render
from .forms import CustomAuthenticationForm, CustomUserCreationForm


def signup_user(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                return redirect("accounts:login")
        except IntegrityError:
            form.add_error(
                "email",
                "This username is already take. Please choose a different one. ",
            )
    else:
        form = CustomUserCreationForm()

    context = {"form": form, "title": "Signup"}

    return render(request, "accounts.html", context)


def login_user(request):
    if request.method == "POST":
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            email = request.POST.get("username", "")
            password = request.POST.get("password", "")
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect("invoice:dashboard")
            else:
                messages.error(request, "Invalid login credentials. Please try again.")
    else:
        form = CustomAuthenticationForm(request)

    context = {
        "form": form,
        "title": "Login",
    }

    return render(request, "accounts.html", context)


def logout_user(request):
    logout(request)
    return redirect("accounts:login")

SimpleInvoice/invoice/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from fpdf import FPDF
from .forms import InvoiceForm
from .models import Invoice


@login_required
def dashboard(request):
    invoices = Invoice.objects.filter(created_by=request.user)
    context = {"invoices": invoices, "title": "Dashboard"}
    return render(request, "dashboard.html", context)


@login_required
def create_invoice(request):
    # Handles the creation of an invoice
    if request.method == "POST":
        form = InvoiceForm(request.POST)
        if form.is_valid():
            invoice = form.save(commit=False)
            invoice.created_by = request.user
            invoice.save()
            return redirect("invoice:detail", invoice.id)
    else:
        form = InvoiceForm()
    back_url = reverse("invoice:dashboard")
    context = {"form": form, "title": "Create an invoice", "url": back_url}

    return render(request, "invoice_form.html", context)


@login_required
def update_invoice(request, invoice_id):
    # Handles the update of an invoice
    invoice = get_object_or_404(Invoice, id=invoice_id)
    if request.method == "POST":
        form = InvoiceForm(request.POST, instance=invoice)
        if form.is_valid():
            form.save()
            return redirect("invoice:detail", invoice.id)
    else:
        form = InvoiceForm(instance=invoice)
    back_url = reverse("invoice:detail", args=[invoice.id])
    context = {
        "form": form,
        "invoice": invoice,
        "title": "Edit the invoice",
        "url": back_url,
    }
    return render(request, "invoice_form.html", context)


@login_required
def create_similar_invoice(request, invoice_id):
    # Handles the creation of a similar invoice
    invoice = get_object_or_404(Invoice, id=invoice_id)
    if request.method == "POST":
        form = InvoiceForm(request.POST, instance=invoice)
        if form.is_valid():
            new = form.save(commit=False)
            new.id = None
            new.save()
            return redirect("invoice:detail", invoice.id)
    else:
        form = InvoiceForm(instance=invoice)
    back_url = reverse("invoice:detail", args=[invoice.id])
    context = {
        "form": form,
        "invoice": invoice,
        "title": "Create a smilar invoice",
        "url": back_url,
    }
    return render(request, "invoice_form.html", context)


@login_required
def delete_invoice(request, invoice_id):
    # Handles the deletion of an invoice
    invoice = get_object_or_404(Invoice, id=invoice_id)
    if request.method == "POST":
        invoice.delete()
        return redirect("invoice:dashboard")
    context = {"title": "Delete the Invoice", "invoice": invoice}
    return render(request, "confirm_delete.html", context)


@login_required
def detail_invoice(request, invoice_id):
    # Displays an invoice details
    invoice = get_object_or_404(Invoice, id=invoice_id)
    back_url = reverse("invoice:dashboard")
    context = {"invoice": invoice, "title": "Invoice details", "url": back_url}
    return render(request, "invoice_details.html", context)


@login_required
def download_invoice(request, invoice_id):
    # Handles creation of invoice in pdf format and make it downloadable
    invoice = get_object_or_404(Invoice, id=invoice_id)

    # Generate the PDF content
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break("auto")

    # Invoice number
    pdf.set_font("Helvetica", "B", size=18)
    pdf.text(10, 10, f"Invoice number: {invoice.invoice_number}")

    # Place of creation, date of issue, and date of service:
    pdf.set_font("Helvetica", "B", size=10)

    # Place of creation
    pdf.text(145, 30, f"Place of creation: {invoice.place_of_creation}")

    # Date of issue:
    pdf.text(145, 35, f"Date of issue: {invoice.date_of_creation.strftime('%Y-%m-%d')}")

    # Date of service
    pdf.text(
        145, 40, f"Date of service: {invoice.date_of_service.strftime('%Y-%m-%d')}"
    )

    # Seller:
    pdf.set_font("helvetica", "B", size=12)
    pdf.text(20, 75, "Seller details:")
    pdf.set_font("helvetica", size=10)

    company_y_position = 80
    pdf.text(20, company_y_position, f"{invoice.company_name}")
    pdf.text(20, company_y_position + 5, f"{invoice.company_street_address}")
    pdf.text(20, company_y_position + 10, f"{invoice.company_city}")
    pdf.text(20, company_y_position + 15, f"{invoice.company_zip_code}")
    pdf.text(20, company_y_position + 20, f"{invoice.company_tax_id}")
    pdf.text(20, company_y_position + 25, f"{invoice.company_phone}")

    # Customer:
    pdf.set_font("helvetica", "B", size=12)
    pdf.text(120, 75, "Customer details:")
    pdf.set_font("helvetica", size=10)

    customer_y_position = 80
    pdf.text(120, customer_y_position, f"{invoice.customer_company_name}")
    pdf.text(120, customer_y_position + 5, f"{invoice.customer_street_address}")
    pdf.text(120, customer_y_position + 10, f"{invoice.customer_city}")
    pdf.text(120, customer_y_position + 15, f"{invoice.customer_zip_code}")
    pdf.text(120, customer_y_position + 20, f"{invoice.customer_tax_id}")
    pdf.text(120, customer_y_position + 25, f"{invoice.customer_phone}")

    # Service type:

    pdf.set_font("helvetica", "B", size=12)
    pdf.text(15, 150, "Service type:")

    service_type_y_position = 155
    pdf.set_font("helvetica", size=10)
    pdf.text(15, service_type_y_position, f"{invoice.service_type_1}")
    if len(invoice.service_type_2) > 1:
        service_type_y_position += 5
        pdf.text(15, service_type_y_position, f"{invoice.service_type_2}")
    if len(invoice.service_type_3) > 1:
        service_type_y_position += 5
        pdf.text(15, service_type_y_position, f"{invoice.service_type_3}")

    # Unit:

    pdf.set_font("helvetica", "B", size=12)
    pdf.text(90, 150, "Unit:")

    unit_y_position = 155
    pdf.set_font("helvetica", size=10)
    pdf.text(90, unit_y_position, f"{invoice.unit_1.capitalize()}")
    if len(invoice.unit_2) > 1:
        unit_y_position += 5
        pdf.text(90, unit_y_position, f"{invoice.unit_2.capitalize()}")
    if len(invoice.unit_3) > 1:
        unit_y_position += 5
        pdf.text(90, unit_y_position, f"{invoice.unit_3.capitalize()}")

    # Amount:
    pdf.set_font("helvetica", "B", size=12)
    pdf.text(115, 150, "Amount:")

    amount_y_position = 155
    pdf.set_font("helvetica", size=10)
    pdf.text(115, amount_y_position, f"{invoice.amount_1}")
    if invoice.amount_2 is not None:
        amount_y_position += 5
        pdf.text(115, amount_y_position, f"{invoice.amount_2}")
    if invoice.amount_3 is not None:
        amount_y_position += 5
        pdf.text(115, amount_y_position, f"{invoice.amount_3}")

    # Price:
    pdf.set_font("helvetica", "B", size=12)
    pdf.text(145, 150, "Price:")

    price_y_position = 155
    pdf.set_font("helvetica", size=10)
    pdf.text(145, price_y_position, f"{invoice.price_1}")
    if invoice.price_2 is not None:
        price_y_position += 5
        pdf.text(145, price_y_position, f"{invoice.price_2}")
    if invoice.price_3 is not None:
        price_y_position += 5
        pdf.text(145, price_y_position, f"{invoice.price_3}")

    # Total price:
    pdf.set_font("helvetica", "B", size=12)
    pdf.text(170, 150, "Total price:")

    total_price_y_position = 155
    pdf.set_font("helvetica", size=10)
    pdf.text(170, total_price_y_position, f"{invoice.total_price_1}")
    if invoice.total_price_2 is not None:
        total_price_y_position += 5
        pdf.text(170, total_price_y_position, f"{invoice.total_price_2}")
    if invoice.total_price_3 is not None:
        total_price_y_position += 5
        pdf.text(170, total_price_y_position, f"{invoice.total_price_3}")

    # Total due:
    pdf.set_font("helvetica", "B", size=10)
    pdf.text(20, 190, f"Total due: ")
    pdf.set_font("helvetica", size=10)
    pdf.text(38, 190, f"{invoice.total_price} {invoice.currency}")
    # Account number:
    pdf.set_font("helvetica", "B", size=10)
    pdf.text(20, 195, f"Account number: ")
    pdf.set_font("helvetica", size=10)
    pdf.text(50, 195, f"{invoice.company_account_number}")

    # Method payment:
    pdf.set_font("helvetica", "B", size=10)
    pdf.text(20, 200, f"Method payment: ")
    pdf.set_font("helvetica", size=10)
    pdf.text(50, 200, f"{invoice.method_payment}")

    # Due date:
    pdf.set_font("helvetica", "B", size=10)
    pdf.text(20, 205, "Due date: ")
    pdf.set_font("helvetica", size=10)
    pdf.text(36, 205, "14 days")

    # Comments:
    if len(invoice.additional_information) > 1:
        pdf.text(70, 240, f"Comments: {invoice.additional_information}")

    # Seller singature:
    pdf.set_font("helvetica", "B", size=8)
    pdf.text(20, 270, "Seller signature:")
    pdf.text(20, 275, "-----------------")

    # Buyer signature:
    pdf.text(150, 270, "Buyer signature:")
    pdf.text(150, 275, "----------------")
    # Output the PDF content
    response = HttpResponse(content_type="application/pdf")
    response[
        "Content-Disposition"
    ] = f"attachment; filename='invoice_{invoice.invoice_number}.pdf'"

    pdf_output = pdf.output(dest="S").encode("latin-1")
    response.write(pdf_output)

    return response

SimpleInvoice/templates/accounts.html
{% extends "base.html" %}

{% block content %}

<div class="flex items-center justify-center mt-36 mb-16">
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="text-red-500">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="text-red-500">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
</div>
<div class="flex items-center justify-center m-30">
    <div class="bg-gray-100 p-8 rounded-md shadow-md">
        <h2 class="text-2xl font-semibold mb-4">{{ title }}</h2>
        
        <form method="post" class="space-y-4">
            {% csrf_token %}
            {% if  title  == "Signup" %}
                <p>{{ form.username.label_tag }}</p>
                <p>{{ form.username }}</p>
                <p>{{ form.email.label_tag }}</p>
                <p>{{ form.email }}</p>
                <p>{{ form.password1.label_tag }}</p>
                <p>{{ form.password1 }}</p>
                <p>{{ form.password2.label_tag }}</p>
                <p>{{ form.password2 }}</p>
            {% elif  title  == "Login" %}
                <p>{{ form.username.label_tag }}</p>
                <p>{{ form.username }}</p>
                <p>{{ form.password.label_tag }}</p>
                <p>{{ form.password }}</p>
            {% endif %}
            <button class="py-2 px-4 bg-zinc-500 text-white rounded-md">{{ title }}</button>
        </form>
    </div>
</div>
{% endblock %}

SimpleInvoice/templates/base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{{ title }}{% endblock %} | Simple Invoice</title>
        {% compress css %}
            <link rel="stylesheet" href="{% static 'src/output.css' %}">
        {% endcompress %}
    </head>
    <body class="flex flex-col min-h-screen bg-gray-100">
        <nav class="fixed top-0 left-0 right-0 p-6 flex items-center justify-between bg-indigo-400">
            <p class="text-xl text-white">Simple Invoice</p>

            <div class="space-x-4 text-white">
                {% if request.user.is_authenticated %}
                    <a href="{% url "invoice:dashboard" %}">Dashboard</a>
                    <a href="{% url 'invoice:create' %}" class="py-2 px-4 bg-zinc-500 text-white rounded-md">Create New Invoice</a>
                    <a href="{% url 'accounts:logout' %}" class="button-warning">Logout</a>
                {% else %}
                    <a href="{% url 'accounts:login' %}" class="py-2 px-4 bg-zinc-600 text-white rounded-md">Login</a>
                    <a href="{% url 'accounts:signup' %}" class="py-2 px-4 bg-zinc-800 text-white rounded-md">Sign up</a>
                {% endif %}
            </div>
        </nav>
        <main class="p-6 flex-1 mt-16">
            
            {% block content %}
            {% endblock %}
        </main>

        <footer class="fixed bottom-0 left-0 right-0 p-6 bg-indigo-400 text-white">
            <p class="text-sm text-center">Copyright (c) 2024 - Simple Invoice</p>
        </footer>
    </body>
</html>

SimpleInvoice/templates/confirm_delete.html
{% extends "base.html" %}


{% block content %}
<div class="flex justify-center items-center mt-36">
    <h1><strong>Delete Invoice</strong></h1>
</div>
<div class="flex justify-center items-center mt-10 ">
    <p>Are you sure you want to delete this invoice?</p>

</div>
<div class="flex justify-center items-center mt-10">
    <form method="post">
        {% csrf_token %}
        <button class="py-2 px-4 bg-red-600 rounded-md text-white mr-3" type="submit">Confirm delete</button>
        <a href="{% url 'invoice:detail' invoice.id %}" class="button-back text-white">Cancel</a>
    </form>
</div>
{% endblock %}

SimpleInvoice/templates/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto p-8">
    <div class="flex justify-center items-center py-6">
        <div>
            {% if invoices %}
                <ul>
                    {% for invoice in invoices %}
                        <li class="mb-4">
                            <a href="{% url 'invoice:detail' invoice.id %}" class="text-indigo-600 hover:underline">
                                Invoice #: <strong>{{ invoice.invoice_number }}</strong> | Creation Date: {{ invoice.date_of_creation }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="text-gray-500">You have not created any invoices yet.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

SimpleInvoice/templates/invoice_details.html
{% extends "base.html" %}

{% block content %}
    <div class="container mx-auto p-8">
        <div class="bg-gray-100 p-4 mb-6 rounded-lg shadow-md">
            <div class="flex items-center justify-between">
                <p class="font-semibold">Date of issue: {{ invoice.date_of_creation }}</p>
                <p class="font-semibold">Date of service: {{ invoice.date_of_service }}</p>
            </div>
        </div>

        <div class="flex justify-center mb-10">
            <div class="flex items-center bg-gray-100 p-4 rounded-lg shadow-md">
                <p class="font-semibold">Invoice number: {{ invoice.invoice_number }}</p>
            </div>
        </div>

        <div class="flex justify-center mb-8">
            <div class="w-2/3 bg-gray-100 p-4 rounded-md shadow-md">
                <div class="flex justify-between mt-5">
                    <div class="ml-6">
                        <p class="mb-2 font-semibold">Seller details:</p>
                        <p>{{ invoice.company_name }}</p>
                        <p>{{ invoice.company_street_address }}</p>
                        <p>{{ invoice.company_city }}</p>
                        <p>{{ invoice.company_zip_code }}</p>
                        <p>{{ invoice.company_tax_id }}</p>
                        <p>Phone: {{ invoice.company_phone }}</p>
                    </div>
                    <div class="mr-6">
                        <p class="mb-2 font-semibold">Buyer details:</p>
                        <p>{{ invoice.customer_company_name }}</p>
                        <p>{{ invoice.customer_street_address }}</p>
                        <p>{{ invoice.customer_city }}</p>
                        <p>{{ invoice.customer_zip_code }}</p>
                        <p>{{ invoice.customer_tax_id }}</p>
                        <p>Phone: {{ invoice.company_phone }}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="flex justify-center">
            <div class="w-2/3 bg-gray-100 p-4 rounded-md shadow-md">
                <div class="flex justify-between mt-3">
                    <div class="ml-4">
                        <p class="font-semibold">Name of service:</p>
                        <p>{{ invoice.service_type_1 }}</p>
                        <p>{{ invoice.service_type_2 }}</p>
                        <p>{{ invoice.service_type_3 }}</p>
                    </div>
                    <div>
                        <p class="font-semibold">Unit:</p>
                        <p>{{ invoice.unit_1 }}</p>
                        {% if invoice.unit_2 is not None %}
                            <p>{{ invoice.unit_2 }}</p>
                        {% endif %}
                        {% if invoice.unit_3 is not None %}
                            <p>{{ invoice.unit_3 }}</p>
                        {% endif %}
                    </div>
                    <div>
                        <p class="font-semibold">Amount:</p>
                        <p>{{ invoice.amount_1 }}</p>
                        {% if invoice.amount_2 is not None %}
                            <p>{{ invoice.amount_2 }}</p>
                        {% endif %}
                        {% if invoice.amount_3 is not None %}
                            <p>{{ invoice.amount_3 }}</p>
                        {% endif %}
                    </div>
                    <div>
                        <p class="font-semibold">Price:</p>
                        <p>{{ invoice.price_1 }}</p>
                        {% if invoice.price_2 is not None %}
                            <p>{{ invoice.price_2 }}</p>
                        {% endif %}
                        {% if invoice.price_3 is not None %}
                            <p>{{ invoice.price_3 }}</p>
                        {% endif %}
                    </div>
                    <div class="mr-4">
                        <p class="font-semibold">Total price:</p>
                        <p>{{ invoice.total_price_1 }}</p>
                        {% if invoice.total_price_2 is not None %}
                            <p>{{ invoice.total_price_2 }}</p>
                        {% endif %}
                        {% if invoice.total_price_3 is not None %}
                            <p>{{ invoice.total_price_3 }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="py-6 flex justify-center p-10">
            <div class="w-2/3">
                <p class="font-semibold">Total due: {{ invoice.total_price }} {{ invoice.currency|upper }}</p>
                <p class="font-semibold">Account number: {{ invoice.company_account_number }}</p>
                <p class="font-semibold">Method payment: {{ invoice.method_payment }}</p>
                <p class="font-semibold">Due date: 14 days</p>
            </div>
        </div>

        {% if invoice.additional_information %}
            <div class="flex justify-center">
                <div class="mb-10 flex items-center">
                    <p class="font-semibold">Comments: {{ invoice.additional_information }}</p>
                </div>
            </div>
        {% endif %}

        <div class="flex justify-center py-4">
            <div class="w-2/3 flex justify-between">
                <div class="ml-4">
                    <p class="font-semibold">Company signature:</p>
                    <p>_________________</p>
                </div>
                <div class="mr-4">
                    <p class="font-semibold">Customer signature:</p>
                    <p>________________</p>
                </div>
            </div>
        </div>
        <div class="flex justify-center">
            <div class="flex items-center mt-8 text-white">
                <a href={{ url }} class="button-back">Back</a>
                <a href={% url 'invoice:create-similar' invoice.id %} class="py-2 px-4 bg-zinc-600 rounded-md text-white mr-3">Create Similar</a>
                <a href="{% url 'invoice:download' invoice.id %}" class="py-2 px-4 bg-zinc-700 rounded-md text-white mr-3">Download</a>
                <a href="{% url 'invoice:update' invoice.id %}" class="py-2 px-4 bg-zinc-900 rounded-md text-white mr-3">Update</a>
                <a href="{% url 'invoice:delete' invoice.id %}" class="button-warning">Delete</a>
            </div>
        </div>
    </div>
{% endblock %}

SimpleInvoice/templates/invoice_form.html
{% extends "base.html" %}

{% block content %}

    <h1 class="text-3xl font-bold text-center p-8">{{ title }}</h1>
    <br/>

    <form method="post" class="flex flex-col space-y-4 mb-16">
        {% csrf_token %}
        
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="border p-4 rounded-md">
                <h2 class="font-bold text-lg">Company Information:</h2>
                <br/>
                {{ form.company_name.label_tag }}
                {{ form.company_name }}
                {{ form.company_street_address.label_tag  }}
                {{ form.company_street_address }}
                {{ form.company_city.label_tag  }}
                {{ form.company_city }}
                {{ form.company_zip_code.label_tag  }}
                {{ form.company_zip_code }}
                {{ form.company_tax_id.label_tag  }}
                {{ form.company_tax_id }}
                {{ form.company_phone.label_tag  }}
                {{ form.company_phone }}
                {{ form.company_account_number.label_tag  }}
                {{ form.company_account_number }}
                
            </div>
            <div class="border p-4 rounded-md">
                <h2 class="font-bold text-lg">Customer Information:</h2>
                <br/>
                {{ form.customer_company_name.label_tag }}
                {{ form.customer_company_name }}
                {{ form.customer_street_address.label_tag }}
                {{ form.customer_street_address }}
                {{ form.customer_city.label_tag }}
                {{ form.customer_city }}
                {{ form.customer_zip_code.label_tag }}
                {{ form.customer_zip_code }}
                {{ form.customer_tax_id.label_tag }}
                {{ form.customer_tax_id }}
                {{ form.customer_phone.label_tag }}
                {{ form.customer_phone }}

            </div>
        </div>

        <hr class="my-6">


        <h2 class="font-bold text-2xl mb-4">Invoice Details:</h2>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div class="mb-4">
                {{ form.place_of_creation.label_tag }}
                {{ form.place_of_creation }}
            </div>

            <div class="mb-4">
                {{ form.date_of_creation.label_tag }}
                {{ form.date_of_creation }}
            </div>

            <div class="mb-4">
                {{ form.date_of_service.label_tag }}
                {{ form.date_of_service }}
            </div>



        </div>

        <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div class="mb-4">
                {{ form.invoice_number.label_tag }}
                {{ form.invoice_number }}
            </div>

            <div class="mb-4">
                {{ form.currency.label_tag }}
                {{ form.currency }}
            </div>

            <div class="mb-4">
                {{ form.method_payment.label_tag }}
                {{ form.method_payment }}
            </div>


        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div class="border p-4 rounded-md">
                {{ form.service_type_1.label_tag }}
                <p class="mb-2">{{ form.service_type_1 }}</p>
                <p class="mb-2">{{ form.service_type_2 }}</p>
                <p class="mb-2">{{ form.service_type_3 }}</p>
            </div>

            <div class="border p-4 rounded-md">
                <div class="grid grid-cols-3 gap-4">
                    <div>
                        {{ form.unit_1.label_tag }}
                        <p class="mb-2">{{ form.unit_1 }}</p>
                        <p class="mb-2">{{ form.unit_2 }}</p>
                        <p class="mb-2">{{ form.unit_3 }}</p>
                    </div>

                    <div>
                        {{ form.amount_1.label_tag }}
                        <p class="mb-2">{{ form.amount_1 }}</p>
                        <p class="mb-2">{{ form.amount_2 }}</p>
                        <p class="mb-2">{{ form.amount_3 }}</p>
                    </div>

                    <div>
                        {{ form.price_1.label_tag }}
                        <p class="mb-2">{{ form.price_1 }}</p>
                        <p class="mb-2">{{ form.price_2 }}</p>
                        <p class="mb-2">{{ form.price_3 }}</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="mb-4">
            {{ form.additional_information.label_tag }}
            {{ form.additional_information }}
        </div>

        <div class="mt-6 flex items-center justify-center text-white">
            <button class="py-2 px-4 bg-zinc-500 rounded-md m-3">Submit</button>
            <a href={{ url}} class="button-back">Back</a>
        </div>
      </form>
  </div>
{% endblock %}